### ISSUE TITLE
_pickle.PicklingError: Can't pickle <built-in function print>: it's not the same object as builtins.print

### ISSUE THREAD

**Issue by xiaoweibit** [TuragaLab/flybody#13]
When running train_dmpo_ray, an error occurred:

Traceback (most recent call last):
  File "/home/xw/Desktop/flybody/flybody/train_dmpo_ray.py", line 190, in <module>
    learner = Learner.remote(replay_server.get_server_address.remote(),
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/actor.py", line 733, in remote
    return self._remote(args=args, kwargs=kwargs, **self._default_options)
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 388, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/actor.py", line 1176, in _remote
    actor_id = worker.core_worker.create_actor(
  File "python/ray/_raylet.pyx", line 4106, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 4111, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 839, in ray._raylet.prepare_args_and_increment_put_refs
  File "python/ray/_raylet.pyx", line 830, in ray._raylet.prepare_args_and_increment_put_refs
  File "python/ray/_raylet.pyx", line 880, in ray._raylet.prepare_args_internal
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/_private/serialization.py", line 556, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/_private/serialization.py", line 534, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/_private/serialization.py", line 481, in _serialize_to_pickle5
    raise e
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/_private/serialization.py", line 476, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/home/xw/anaconda3/envs/flybody/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
_pickle.PicklingError: Can't pickle <built-in function print>: it's not the same object as builtins.print

**Comment by alexispomares** [comment]
having this issue as well, @vaxenburg no plans to fix this at all?

**Comment by alexispomares** [comment]
FYI @vaxenburg this error is simply fixed by pinning Ray to version `v2.44.0`
